name: Check CMake file list and VC++ projects
on: [push, pull_request]
jobs:
  filelists:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: |
        ./tools/check_filelists.sh
